[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/sitemap.xml"
  to = "https://zhodvtkvhwbiwdgzocmk.supabase.co/functions/v1/sitemap"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200