// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewgpmgvmzlkzupbptuby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3Z3BtZ3ZtemxrenVwYnB0dWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDk2NTIsImV4cCI6MjA3MDQ4NTY1Mn0.OqO7WEurCB0g0bIt0jsKYLI29K8AFyoY-3Q3hYvAgTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});